AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample stream processing reconcilliation

  '
Globals:
  Function:
    Runtime: go1.x
Parameters:
  Env:
    Default: Dev
    Type: String
Resources:
  AppStream:
    Properties:
      Name:
        Fn::Join:
        - '-'
        - - WreakStream
          - Ref: Env
      ShardCount: 1
    Type: AWS::Kinesis::Stream
  ProcessedTopic:
    Properties:
      DisplayName:
        Fn::Join:
        - '-'
        - - WreakStreamTopic
          - Ref: Env
      TopicName:
        Fn::Join:
        - '-'
        - - WreakStreamTopic
          - Ref: Env
    Type: AWS::SNS::Topic
  StreamProcessor:
    Properties:
      CodeUri: s3://sampack-97068/c49d6c8208b854048fef3c43406219e7
      Environment:
        Variables:
          TOPIC:
            Ref: ProcessedTopic
      Events:
        StreamEvent:
          Properties:
            BatchSize: 50
            StartingPosition: LATEST
            Stream:
              Fn::GetAtt:
              - AppStream
              - Arn
          Type: Kinesis
      FunctionName:
        Fn::Join:
        - '-'
        - - StreamProcessor
          - Ref: Env
      Handler: bin/streamreader
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
