AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcStackName:
    Type: String
    Default: vpc-dev

Resources:

  ReconSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: some crap for a required field
      SubnetIds:
        - Fn::ImportValue: !Join [ -, [ CacheVpc, Ref: "VpcStackName", Subnet1 ]]
        - Fn::ImportValue: !Join [ -, [ CacheVpc, Ref: "VpcStackName", Subnet2 ]]

  ReconCache:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t2.micro
      Engine: memcached
      NumCacheNodes: 1
      Port: 8765
      CacheSubnetGroupName: 
        Ref: ReconSubnetGroup
      VpcSecurityGroupIds:
        - 
          Fn::ImportValue: !Join [ -, [ CacheVpc, Ref: "VpcStackName", LambdaSG ]]

Outputs:
  Endpoint:
    Value: !GetAtt ReconCache.ConfigurationEndpoint.Address
    Export:
      Name: !Join [ -, [ ReconCache, Ref: "AWS::StackName", Endpoint ]]

  Port:
    Value: !GetAtt ReconCache.ConfigurationEndpoint.Port
    Export:
      Name: !Join [ -, [ ReconCache, Ref: "AWS::StackName", Port ]]

